FROM node:16.14.0-alpine as builder

WORKDIR /app

COPY . .

RUN yarn --frozen-lockfile
RUN yarn build

FROM node:16.14.0-alpine

WORKDIR /app

COPY package.json ./
COPY yarn.lock .

RUN yarn --production=true --frozen-lockfile

COPY --from=builder /app/dist ./dist

EXPOSE 5000

CMD ["yarn", "start:prod"]
