version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: create-training-template-mysql
    restart: always
    volumes:
      - create-training-template-mysql-vol:/var/lib/mysql
    cap_add:
      - SYS_NICE
    networks:
      - create-training-template-network
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - ${MYSQL_HOST_PORT}:${MYSQL_PORT}

  app:
    container_name: create-training-template-app
    networks:
      - create-training-template-network
    tty: true
    stdin_open: true
    build: ./docker/app
    ports:
      - ${NEST_HOST_PORT}:${PORT}
    depends_on:
      - mysql
    volumes:
      - .:/app

volumes:
  create-training-template-mysql-vol:

networks:
  create-training-template-network:
    driver: bridge
